name: ids_normal_note
description: A simple, efficient note taking app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core Features for Notes
  speech_to_text: ^6.6.0
  record: ^5.1.0
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # UI & Utils
  google_fonts: ^6.1.0
  uuid: ^4.3.3
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
